# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff485a180f0fbc0c197e69e50c3759c3523498761840c223d4c1fdb8d21fc698ce90e7d382a428ce7fde76b7ce653aa454ebb3fee885f4dc1ab5e86ee88ccb04

test:
  secret_key_base: 3457670604aebd1ff76aa633a3ed4119c1cdef22fa5aa4f7b53db6eafb3088dbae894e4592e700ca736d03fe1e830bf36c8c887f96f5d4efd37923974a8b629a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
